resources:

- name: bootstrap
  type: git
  source:
    branch: master
    uri: https://github.com/thaddeusa/bootstrap-concourse.git

jobs:

- name: hi-there
  plan:
  - get: bootstrap
  - task: hi-there
    file: bootstrap/ci/tasks/test/hi-there.yml
