resources:

- name: bootstrap
  type: git
  source:
    branch: master
    uri: git@bitbucket.org:thaddeusa/bootstrap.git
    private_key: ((bitbucket_private_key))

jobs:

- name: hi-there
  plan:
  - get: bootstrap
  - task: hi-there
    file: bootstrap/ci/tasks/hi-there.yml
