resources:

- name: bootstrap
  type: git
  source:
    branch: master
    uri: git@github.com:thaddeusa/bootstrap-concourse.git

jobs:

- name: hi-there
  plan:
  - get: bootstrap
  - task: hi-there
    file: bootstrap/ci/tasks/hi-there.yml
